### PR TITLE
add hypernode:performance to magerun2 systemwide

### PR DESCRIPTION
**Pull request by vdloo**
install the magerun2 [compatible modules](https://github.com/Hypernode/hypernode-magerun/blob/master/n98-magerun2.yaml) systemwide so people don't have to manually [link the module](https://github.com/Hypernode/hypernode-magerun#installation) in their home directory to benchmark magento 2 shops
```
app@j6yrvm-suusshop-magweb-do:~$ magerun2 | grep hypernode 
 hypernode
  hypernode:performance           Generate a performance report based on sitemaps.
```

### CODE REVIEW

**Review by genisd — APPROVED** [review]
if it's intentional to symlink the same modules to magerun and magerun2 ?
then :+1:

**Comment by genisd** [comment]
travis doesn't like this in combination with php5.5 and older magento's by the looks of things.
not sure if we still want to support magento version 1.4/5/6/7

**Comment by vdloo** [comment]
yeah that's intentional, the enabled modules (that work with magerun2) are configured [here](https://github.com/Hypernode/hypernode-magerun/blob/master/n98-magerun2.yaml#L6). about the failing tests, yeah those seem unrelated. I'll make sure that it's broken on master [as well](https://github.com/Hypernode/hypernode-magerun/pull/54) and if so then we can just merge this (and we should find out why the build fails some time)

**Comment by vdloo** [comment]
master also fails on [this unrelated problem](https://travis-ci.org/Hypernode/hypernode-magerun/builds/271654676), merging

**Pull request merged**
