### PR TITLE
use googlebot ua for crawling

### PR DESCRIPTION
**Pull request by vdloo**
Identify as a crawler so we don't bypass the Varnish cache on shops with magento-turpentine 0.1.6 or later
https://github.com/nexcess/magento-turpentine/blob/e3577315cdd8fb35b1bff812d2cf1b61e1b76c13/CHANGELOG.md#release-016
https://github.com/nexcess/magento-turpentine/blob/e3577315cdd8fb35b1bff812d2cf1b61e1b76c13/app/code/community/Nexcessnet/Turpentine/etc/config.xml#L66

### CODE REVIEW

**Comment by genisd** [comment]
we might get issues claiming to be google while not coming from a google IP range.
but yeah let's try! :)
:+1:

**Review by genisd — APPROVED** [review]

**Comment by vdloo** [comment]
maybe using `ApacheBench` would be safer. we could also implement a cookiejar instead but that's more work.

**Comment by vdloo** [comment]
Changed the UA to ApacheBench. That's a bit safer to block if people want to stop their site from being curled by this tool.

**Comment by vdloo** [comment]
master is failing with:
```
PHP Fatal error:  Class 'N98\Magento\Command\PHPUnit\TestCase' not found in /data/web/public/tests/Hypernode/Magento/Command/Hypernode/Config/GenerateMapsCommandTest.php on line 21
```

**Pull request merged**
